version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - /srv/quickload/docker-volumes/wordpress/db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - ./environment/production.env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - /srv/quickload/docker-volumes/wordpress/html:/var/www/html
      - /etc/letsencrypt/archive/noxlan.co.uk:/var/www/noxlan.co.uk:ro
    ports:
      - "192.168.1.100:80:80"
    restart: unless-stopped
    env_file:
      - ./environment/production.env
